# Generated by Django 6.0.7 on 2026-08-03 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ASSIGN_ROLE", "Assign Role"),
                            ("REMOVE_ROLE", "Remove Role"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PROFILE_UPDATE", "Profile Update"),
                            ("PROFILE_PICTURE_UPLOAD", "Profile Picture Upload"),
                            ("PROFILE_PICTURE_REMOVE", "Profile Picture Remove"),
                            ("ROLE_ACTIVATE", "Role Activate"),
                            ("ROLE_DEACTIVATE", "Role Deactivate"),
                            ("USER_REGISTER", "User Register"),
                            ("USER_CREATE", "User Create"),
                            ("USER_UPDATE", "User Update"),
                            ("USER_DEACTIVATE", "User Deactivate"),
                            ("USER_ACTIVATE", "User Activate"),
                            ("USER_LOCK", "User Lock"),
                            ("USER_UNLOCK", "User Unlock"),
                            ("USER_SOFT_DELETE", "User Soft Delete"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
