# Generated by Django 6.0.7 on 2026-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("IS_ARCHIVED", "Is Archived"),
                    ("RESTORED", "Restored"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("ASSIGN_ROLE", "Assign Role"),
                    ("REMOVE_ROLE", "Remove Role"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PROFILE_UPDATE", "Profile Update"),
                    ("PROFILE_PICTURE_UPLOAD", "Profile Picture Upload"),
                    ("PROFILE_PICTURE_REMOVE", "Profile Picture Remove"),
                    ("ROLE_ACTIVATE", "Role Activate"),
                    ("ROLE_DEACTIVATE", "Role Deactivate"),
                    ("USER_REGISTER", "User Register"),
                    ("USER_CREATE", "User Create"),
                    ("USER_UPDATE", "User Update"),
                    ("USER_DEACTIVATE", "User Deactivate"),
                    ("USER_ACTIVATE", "User Activate"),
                    ("USER_LOCK", "User Lock"),
                    ("USER_UNLOCK", "User Unlock"),
                    ("USER_SOFT_DELETE", "User Soft Delete"),
                    ("CREATE_REVIEW_REQUEST", "Create Review Request"),
                    ("SUBMIT_REVIEW_REQUEST", "Submit Review Request"),
                    ("CREATE_REVIEW_ASSIGNMENT", "Create Review Assignment"),
                    ("START_REVIEW", "Start Review"),
                    ("CREATE_REVIEW_DECISION", "Create Review Decision"),
                    ("CREATE_REVIEW_COMMENT", "Create Review Comment"),
                ],
                max_length=255,
            ),
        ),
    ]
