# Generated by Django 6.0.7 on 2026-08-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewassignment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="reviewdecision",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewdecision",
            name="reviewer",
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_REVIEW", "In Review"),
                    ("COMPLETED", "Completed"),
                    ("SKIPPED", "Skipped"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reviewdecision",
            name="assignment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision",
                to="reviews.reviewassignment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="reviews.comment",
            ),
        ),
        migrations.AlterField(
            model_name="reviewdecision",
            name="decision",
            field=models.CharField(
                choices=[
                    ("APPROVE", "Approve"),
                    ("REJECT", "Reject"),
                    ("REQUEST_CHANGES", "Request Changes"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_REVIEW", "In Review"),
                    ("CHANGES_REQUESTED", "Changes Requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_requests",
                to="documents.documentversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewassignment",
            constraint=models.UniqueConstraint(
                fields=("review", "reviewer"), name="unique_review_assignment"
            ),
        ),
        migrations.RemoveField(
            model_name="reviewassignment",
            name="is_completed",
        ),
    ]
