# Generated by Django 6.0.7 on 2026-08-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_reviewassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewdecision",
            name="assignment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision",
                to="reviews.reviewassignment",
            ),
        ),
    ]
